name: install cache
on: push

jobs:
  jstest1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#       - name: Get npm cache directory
#         id: npm-cache
#         run: |
#           echo "::set-output name=dir::$(npm config get cache)"
#       - uses: actions/cache@v2
#         with:
#           path: ${{ steps.npm-cache.outputs.dir }}
#           key: ${{ runner.os }}-check
      - name: create directory
        run: |
          mkdir -p ./installhere/node_modules

      - name: Cache node modules
        continue-on-error: true
        id: cachestep
        uses: actions/cache@v2
        with:
          path: installhere/node_modules
          key: ${{ runner.os }}-check
      - name: install
        if: steps.cachestep.outputs.cache-hit != 'true'
        run: |
          npm install -g --prefix ./installhere puppeteer-cli --unsafe-perm=true
      - name: add path
        run: |
          export PATH=$PATH:/bin:/${{github.workspace}}/installhere/lib/node_modules
      - name: check 
        continue-on-error: true
        run: |
          pwd
          echo ----------------
          cd /usr/local/lib/node_modules
          ls -al | grep puppeteer
      - run: |
          puppeteer print https://github.com/JarvusInnovations/puppeteer-cli puppeteer-cli.pdf
