name: install cache
on: push

jobs:
  jstest1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create directory
        run: |
          mkdir -p ./installhere    # create a directory for installation
      - name: Cache node modules
        id: cachestep
        uses: actions/cache@v2
        with:
          path: installhere
          key: ${{ runner.os }}-check   # you can change the key if you don't want to cache.
      - name: install
        if: steps.cachestep.outputs.cache-hit != 'true'   # if cache hit, skip the installation
        run: |
          npm install -g --prefix ./installhere puppeteer-cli --unsafe-perm=true   # install in the desired folder
        
      - name: set the PATH and use puppeteer   # check
        run: |
          export PATH=$PATH:${{github.workspace}}/installhere/bin   # add to $PATH for command invoke
          puppeteer print https://github.com/JarvusInnovations/puppeteer-cli puppeteer-cli.pdf
