name: list check run
on: push

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'authorization: Bearer ${{ secrets.PAT1 }}' \
            https://api.github.com/repos/weide-zhou/ticket13/actions/runs|jq -r '.[1] | .id'
