name: list check run
on: push

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/weide-zhou/ticket13/actions/runs?per_page=100&page=12
