name: PR Comment

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  PR-Comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: PR Comment
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':warning: Test!'
            })
