name: manual trigger speficy user
env:
  passwd: ${{ secrets.passwd }}
on:
  workflow_dispatch:
    inputs:
      passwd:
        description: 'check who you are'
        required: true


jobs:
  job1:
    if: github.event.inputs.name==$passwd
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
