name: PR Comment

on:
  pull_request:

jobs:
#   PR-Comment:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Get run URL
#       run: |
#         body=$(<run.txt)
#         echo $body
#         curl --request POST \
#         --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
#         --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
#         --header 'Accept: application/vnd.github.v3+json' \
#         --data '{
#           "body": "'"$body"'"
#           }'
  PR-Comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get the run URL
      run: |
        echo "::set-env name=body::$(<run.txt)"
    - run: echo $body
#     - name: Get run URL
#       run: |
#         body=$(<run.txt)
#         echo -------
#         echo $body
    - name: PR Comment
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: ${{ github.event.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{env.body}}
          })
