name: create wiki
on:
  milestone:
    types: [closed]

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"
    - name: Upload Release Notes to Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        ACTION_MAIL: weide@outlook.com
        ACTION_NAME: wade
        GH_PAT: ${{ secrets.PAT1 }}
        MD_FOLDER: temp_release_notes
        OWNER: weide-zhou
        REPO_NAME: ticket34
        SKIP_MD: README.md
