name: workflow run
on:
  workflow_run:
    workflows: ["issue comment"]
    branches: [B1]
    types:
      - requested
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
